# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EI5KEIN0XWLDJAhweSeIJb_1TxNzMRpO
"""

import pandas as pd
df = pd.DataFrame({'Ism': ['Boynazar','Muhsinjon','Alijon','Sarvinoz','Muxbira','Farog`at','Shaxzod','Asrorbek','Muhammadjon','Muhammadsher'],
                   'Familyasi': ['Toxtasinov','Yusufjonov','Boymirzayev','Abdurasulova','Yo`lchiyeva','Adhamova','Qo`zimurodov','Ubaydullayev','Xonqulov','Inomov'],
                   'Yoshi': ['18','19','19','19','20','18','21','19','19','19'],
                   'Kursi': ['2','2','2','2','2','2','2','2','2','2']
})
print (df)

df.to_excel('guruh.xlsx', index=False, sheet_name='Sheet1')